name: trigger gitlab job
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        host: "https://gitlab.com/sergio.h/ci-github"
        debug: true
        token: ${{ secrets.TOKEN }}
        project_id: 22288234
