name: trigger gitlab job
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      run: curl -X POST -F token=${{ secrets.TOKEN }} -F ref=master https://gitlab.com/api/v4/projects/22288234/trigger/pipeline
